/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Class.*;
import Collage_main.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;



public class new_reveal extends javax.swing.JFrame {

   
    public new_reveal() throws SQLException {
        
        new_reveal_f n = new new_reveal_f();
        DefaultComboBoxModel com = new DefaultComboBoxModel(n.show_doctor_name());     
        Combo_select_person_patient.setModel(com);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panal1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Butt_exit_patient = new javax.swing.JButton();
        Butt_submit_patient = new javax.swing.JButton();
        Tf_name_patient = new javax.swing.JTextField();
        Tf_phone_patient = new javax.swing.JTextField();
        Tf_e_mail_patient = new javax.swing.JTextField();
        Tf_add_patient = new javax.swing.JTextField();
        Tf_age_patient = new javax.swing.JTextField();
        national_id_patient = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Combo_select_person_patient = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tf_symptons_patient = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Reveal (Patient)");

        panal1.setBackground(new java.awt.Color(185, 219, 237));
        panal1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Information ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Phone");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("E-mail");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Age");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("National ID");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Symptoms :");

        Butt_exit_patient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Butt_exit_patient.setText("Exit");
        Butt_exit_patient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 9, 9)));
        Butt_exit_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt_exit_patientActionPerformed(evt);
            }
        });

        Butt_submit_patient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Butt_submit_patient.setText("Submit");
        Butt_submit_patient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 49, 201)));
        Butt_submit_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt_submit_patientActionPerformed(evt);
            }
        });

        Tf_name_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_name_patientActionPerformed(evt);
            }
        });

        Tf_e_mail_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_e_mail_patientActionPerformed(evt);
            }
        });

        Tf_add_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_add_patientActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Select Doctor:");

        Combo_select_person_patient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Combo_select_person_patient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        Combo_select_person_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_select_person_patientActionPerformed(evt);
            }
        });

        Tf_symptons_patient.setColumns(20);
        Tf_symptons_patient.setRows(5);
        jScrollPane1.setViewportView(Tf_symptons_patient);

        javax.swing.GroupLayout panal1Layout = new javax.swing.GroupLayout(panal1);
        panal1.setLayout(panal1Layout);
        panal1Layout.setHorizontalGroup(
            panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panal1Layout.createSequentialGroup()
                .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panal1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(panal1Layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(Butt_exit_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(Butt_submit_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panal1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panal1Layout.createSequentialGroup()
                                .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panal1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(Tf_age_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panal1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(national_id_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel8)
                            .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panal1Layout.createSequentialGroup()
                                    .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(38, 38, 38)
                                    .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panal1Layout.createSequentialGroup()
                                            .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Tf_phone_patient, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                                .addComponent(Tf_name_patient))
                                            .addGap(115, 115, 115)
                                            .addComponent(jLabel9))
                                        .addGroup(panal1Layout.createSequentialGroup()
                                            .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Tf_add_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Tf_e_mail_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(115, 115, 115)
                                            .addComponent(Combo_select_person_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panal1Layout.setVerticalGroup(
            panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panal1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panal1Layout.createSequentialGroup()
                        .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Tf_name_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tf_phone_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tf_e_mail_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panal1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panal1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(Tf_add_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panal1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Combo_select_person_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))))
                .addGap(15, 15, 15)
                .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Tf_age_patient, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(national_id_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(panal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Butt_submit_patient, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(Butt_exit_patient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Butt_exit_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt_exit_patientActionPerformed
       exit ex = new exit();
       this.setVisible(false);
        try {
            ex.exit();
        } catch (InterruptedException ex1) {
           
        }
    }//GEN-LAST:event_Butt_exit_patientActionPerformed

    private void Butt_submit_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt_submit_patientActionPerformed
        new_reveal_f nr =new new_reveal_f();
        Patient p =new Patient();
        p.name=Tf_name_patient.getText();
        p.phone=(Tf_phone_patient.getText());
        p.email=Tf_e_mail_patient.getText();
        p.address=Tf_add_patient.getText();
        p.age=Integer.parseInt(Tf_age_patient.getText());
        p.national_id=(national_id_patient.getText());
        p.symptom=Tf_symptons_patient.getText();
        p.doctor_id= (int)Combo_select_person_patient.getSelectedIndex();
        try {
            nr.new_reveal_submit(p);
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(this, "Make sure that all information is right!");
        }
        
        
        
        
    }//GEN-LAST:event_Butt_submit_patientActionPerformed

    private void Tf_name_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_name_patientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_name_patientActionPerformed

    private void Tf_e_mail_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_e_mail_patientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_e_mail_patientActionPerformed

    private void Tf_add_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_add_patientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_add_patientActionPerformed

    private void Combo_select_person_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_select_person_patientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_select_person_patientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_reveal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_reveal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_reveal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_reveal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new new_reveal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(new_reveal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Butt_exit_patient;
    private javax.swing.JButton Butt_submit_patient;
    private javax.swing.JComboBox<String> Combo_select_person_patient;
    private javax.swing.JTextField Tf_add_patient;
    private javax.swing.JTextField Tf_age_patient;
    private javax.swing.JTextField Tf_e_mail_patient;
    private javax.swing.JTextField Tf_name_patient;
    private javax.swing.JTextField Tf_phone_patient;
    private javax.swing.JTextArea Tf_symptons_patient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField national_id_patient;
    private javax.swing.JPanel panal1;
    // End of variables declaration//GEN-END:variables
}
